[ 2024-09-01 14:17:08,723 ] 97 werkzeug - WARNING -  * Debugger is active!
[ 2024-09-01 14:17:08,732 ] 97 werkzeug - INFO -  * Debugger PIN: 119-654-287
[ 2024-09-01 14:17:13,115 ] 97 werkzeug - INFO - 127.0.0.1 - - [01/Sep/2024 14:17:13] "GET / HTTP/1.1" 200 -
[ 2024-09-01 14:17:14,357 ] 41 root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:17:14,357 ] 26 root - INFO - Exporting data from mongodb
[ 2024-09-01 14:17:14,358 ] 30 root - INFO - Saving exported data into feature store file path: artifacts/09_01_2024_14_17_07/data_ingestion
[ 2024-09-01 14:17:20,168 ] 32 root - INFO - Shape of dataset: (11055, 31)
[ 2024-09-01 14:17:20,216 ] 44 root - INFO - Got the data from mongodb
[ 2024-09-01 14:17:20,216 ] 45 root - INFO - Exited initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:17:20,216 ] 123 root - INFO - Entered initiate_data_validation method of Data_Validation class
[ 2024-09-01 14:17:20,216 ] 125 root - INFO - Initiated data validation for the dataset
[ 2024-09-01 14:17:20,217 ] 41 root - INFO - Error in valuesFromSchema in data_validation.py
[ 2024-09-01 14:17:20,250 ] 48 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-09-01 14:17:20,268 ] 83 root - INFO - Unwanted spaces removal Successful.
Exited the remove_unwanted_spaces method of the Preprocessor class
[ 2024-09-01 14:17:20,291 ] 38 root - INFO - Entered the save_object method of MainUtils class
[ 2024-09-01 14:17:20,291 ] 45 root - INFO - Exited the save_object method of MainUtils class
[ 2024-09-01 14:17:20,292 ] 104 root - INFO - Splitting training and testing input and target feature
[ 2024-09-01 14:17:20,292 ] 105 root - INFO - Extracting model config file path
[ 2024-09-01 14:17:20,292 ] 52 root - INFO - Entered the load_object method of MainUtils class
[ 2024-09-01 14:17:20,292 ] 56 root - INFO - Exited the load_object method of MainUtils class
[ 2024-09-01 14:17:20,292 ] 107 root - INFO - Extracting model config file path
[ 2024-09-01 14:17:46,559 ] 119 root - INFO - Best found model on both training and testing dataset
[ 2024-09-01 14:17:46,559 ] 121 root - INFO - Saving model at path: artifacts/09_01_2024_14_17_07/model_trainer/trained_model/model.pkl
[ 2024-09-01 14:17:46,560 ] 38 root - INFO - Entered the save_object method of MainUtils class
[ 2024-09-01 14:17:46,566 ] 45 root - INFO - Exited the save_object method of MainUtils class
[ 2024-09-01 14:17:46,576 ] 97 werkzeug - INFO - 127.0.0.1 - - [01/Sep/2024 14:17:46] "GET /train HTTP/1.1" 200 -
[ 2024-09-01 14:19:25,798 ] 41 root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:19:25,799 ] 26 root - INFO - Exporting data from mongodb
[ 2024-09-01 14:19:25,799 ] 30 root - INFO - Saving exported data into feature store file path: artifacts/09_01_2024_14_17_07/data_ingestion
[ 2024-09-01 14:19:29,595 ] 32 root - INFO - Shape of dataset: (11055, 31)
[ 2024-09-01 14:19:29,644 ] 44 root - INFO - Got the data from mongodb
[ 2024-09-01 14:19:29,645 ] 45 root - INFO - Exited initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:19:29,645 ] 123 root - INFO - Entered initiate_data_validation method of Data_Validation class
[ 2024-09-01 14:19:29,645 ] 125 root - INFO - Initiated data validation for the dataset
[ 2024-09-01 14:19:29,645 ] 41 root - INFO - Error in valuesFromSchema in data_validation.py
[ 2024-09-01 14:19:29,724 ] 48 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-09-01 14:19:29,744 ] 83 root - INFO - Unwanted spaces removal Successful.
Exited the remove_unwanted_spaces method of the Preprocessor class
[ 2024-09-01 14:19:29,766 ] 38 root - INFO - Entered the save_object method of MainUtils class
[ 2024-09-01 14:19:29,767 ] 45 root - INFO - Exited the save_object method of MainUtils class
[ 2024-09-01 14:19:29,768 ] 104 root - INFO - Splitting training and testing input and target feature
[ 2024-09-01 14:19:29,768 ] 105 root - INFO - Extracting model config file path
[ 2024-09-01 14:19:29,768 ] 52 root - INFO - Entered the load_object method of MainUtils class
[ 2024-09-01 14:19:29,768 ] 56 root - INFO - Exited the load_object method of MainUtils class
[ 2024-09-01 14:19:29,768 ] 107 root - INFO - Extracting model config file path
[ 2024-09-01 14:20:19,149 ] 97 werkzeug - INFO - 127.0.0.1 - - [01/Sep/2024 14:20:19] "GET / HTTP/1.1" 200 -
[ 2024-09-01 14:20:20,904 ] 97 werkzeug - INFO - 127.0.0.1 - - [01/Sep/2024 14:20:20] "GET / HTTP/1.1" 200 -
[ 2024-09-01 14:20:26,994 ] 41 root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:20:26,996 ] 26 root - INFO - Exporting data from mongodb
[ 2024-09-01 14:20:26,996 ] 30 root - INFO - Saving exported data into feature store file path: artifacts/09_01_2024_14_17_07/data_ingestion
[ 2024-09-01 14:20:31,924 ] 32 root - INFO - Shape of dataset: (11055, 31)
[ 2024-09-01 14:20:32,206 ] 44 root - INFO - Got the data from mongodb
[ 2024-09-01 14:20:32,206 ] 45 root - INFO - Exited initiate_data_ingestion method of Data_Ingestion class
[ 2024-09-01 14:20:32,207 ] 123 root - INFO - Entered initiate_data_validation method of Data_Validation class
[ 2024-09-01 14:20:32,207 ] 125 root - INFO - Initiated data validation for the dataset
[ 2024-09-01 14:20:32,208 ] 41 root - INFO - Error in valuesFromSchema in data_validation.py
[ 2024-09-01 14:20:32,368 ] 48 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-09-01 14:20:32,441 ] 83 root - INFO - Unwanted spaces removal Successful.
Exited the remove_unwanted_spaces method of the Preprocessor class
[ 2024-09-01 14:20:32,607 ] 38 root - INFO - Entered the save_object method of MainUtils class
[ 2024-09-01 14:20:32,609 ] 45 root - INFO - Exited the save_object method of MainUtils class
[ 2024-09-01 14:20:32,611 ] 104 root - INFO - Splitting training and testing input and target feature
[ 2024-09-01 14:20:32,611 ] 105 root - INFO - Extracting model config file path
[ 2024-09-01 14:20:32,611 ] 52 root - INFO - Entered the load_object method of MainUtils class
[ 2024-09-01 14:20:32,612 ] 56 root - INFO - Exited the load_object method of MainUtils class
[ 2024-09-01 14:20:32,612 ] 107 root - INFO - Extracting model config file path
[ 2024-09-01 14:21:20,945 ] 97 werkzeug - INFO -  * Detected change in '/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/app.py', reloading
[ 2024-09-01 14:21:21,384 ] 28 concurrent.futures - ERROR - exception calling callback for <Future at 0x16bb00280 state=finished returned list>
Traceback (most recent call last):
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/externals/loky/_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/parallel.py", line 828, in __call__
    self._dispatch_new()
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/parallel.py", line 843, in _dispatch_new
    self.parallel.dispatch_next()
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/parallel.py", line 1429, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/parallel.py", line 1517, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/parallel.py", line 1418, in _dispatch
    job = self._backend.apply_async(batch, callback=batch_tracker)
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 588, in apply_async
    future = self._workers.submit(func)
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/externals/loky/reusable_executor.py", line 225, in submit
    return super().submit(fn, *args, **kwargs)
  File "/Users/adityachaudhary/Desktop/Important Projects/Data Science/Phishing-Classifier/env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 1228, in submit
    raise ShutdownExecutorError(
joblib.externals.loky.process_executor.ShutdownExecutorError: cannot schedule new futures after shutdown
